In [106]:
import numpy as np
import tensorflow as tf
print(np.maximum(0,np.sign(1-np.array([1.,-1.0,0.0]))))

[ 0.  1.  1.]


In [94]:
f = np.array([1.0,2.0,3.0,4.0]).reshape(-1,1)
y = np.array([[1.0,2.0,3.0,4.0], [1.0,2.0,3.0,4.0]]).reshape(-1,2)
print(f, f.shape)
print(y, y.shape)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]] (4, 1)
[[ 1.  2.]
 [ 3.  4.]
 [ 1.  2.]
 [ 3.  4.]] (4, 2)


In [100]:
np.sum(np.multiply(f,y), axis=0)

array([ 22.,  32.])

In [2]:
dataset = {}
dataset[1] = (1,'S', 44,23)
dataset[2] = (2, 'M', 10, 20)
print(np.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [4]:
print(len(dataset), type(dataset), len(dataset[1]), (type(dataset[1][1])))

2 <class 'dict'> 4 <class 'str'>


In [5]:
print([[dataset[i+1][j] if dataset[i+1] == for j in range(len(dataset[i+1]))] for i in range(len(dataset))])

SyntaxError: invalid syntax (<ipython-input-5-390b4ac8f9f1>, line 1)

In [ ]:
x = list()
print(x)

In [ ]:
feature_columns = ['A', 'B', 'C']
check = ['D', 'B']
print([ 1 if check[i] in feature_columns else 0 for i in range(len(check))] )

In [ ]:
x = np.array([[1, 2], [3, 4], [5,6]])
L =[0,1]

In [ ]:
print(x[L,:])

In [ ]:
b = np.array([[i] for i in range(len(x))])

In [ ]:
print(b[L,:])

In [6]:
# X_new = np.concatenate([x,b], axis=1)
from random import shuffle

In [7]:
print(shuffle(X_new), X_new)


NameError: name 'X_new' is not defined

In [8]:
print(np.random.random((3,1)))

[[ 0.63576374]
 [ 0.80989251]
 [ 0.89919508]]


In [9]:
w = np.ones((3,1))

In [10]:
print(np.dot(X_new, w))

NameError: name 'X_new' is not defined

In [11]:
print(X_new)

NameError: name 'X_new' is not defined

In [12]:
A = [[1, 2 ],[3,4],[5,6]]
b = [[1],[9],[25]]

In [13]:
print(A[(0,1)])

TypeError: list indices must be integers or slices, not tuple

In [14]:
print(comb)

NameError: name 'comb' is not defined

In [15]:
print(map(shuffle,comb))

NameError: name 'comb' is not defined

In [16]:
rand_list = list([np.random.randint(0, len(A)-1)])

In [17]:
print(rand_list)
import random

[0]


In [18]:
print(random.sample(range(0, len(A)), len(A)))

[1, 2, 0]


In [19]:
import numpy as np
import random
rand_list =random.sample(range(0, len(A)), len(A))
print([A[i] for i in rand_list])
print([b[i] for i in rand_list])

[[5, 6], [1, 2], [3, 4]]
[[25], [1], [9]]


In [20]:
print(A)
print(b)

[[1, 2], [3, 4], [5, 6]]
[[1], [9], [25]]


In [21]:
import numpy as np
print(np.array(A)*np.array(b))
print(np.dot(np.transpose(np.array(b)), np.array(A) ))

[[  1   2]
 [ 27  36]
 [125 150]]
[[153 188]]


In [22]:
import numpy as np

In [11]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [12]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [59]:
print(sum(sum(np.power(A, 2))))

91


In [60]:
np.sum(np.power(A,2))

91

In [27]:

def one_hot_bldg_type(bldg_type):
    """Builds the one-hot encoding vector.

    Args:
        bldg_type(str): String indicating the building type.

    Returns:
        ret(list): A list representing the one-hot encoding vector.
            (e.g. for 1Fam building type, the returned list should be
            [1,0,0,0,0].
    """
    type_to_id = {'1Fam': 0,
                  '2FmCon': 1,
                  'Duplx': 2,
                  'TwnhsE': 3,
                  'TwnhsI': 4,
                  }
    ret = [0, 0, 0, 0, 0]
    ret[type_to_id[bldg_type]]=1
            
    #pass
    return ret


In [63]:
b = np.array([[1], [9],[25]])

In [66]:
print([b, A])

[array([[ 1],
       [ 9],
       [25]]), array([[1, 2],
       [3, 4],
       [5, 6]])]


In [69]:
permutation = np.random.permutation(A.shape[0])
print(permutation )
print(A[permutation])
print(b[permutation])

[0 2 1]
[[1 2]
 [5 6]
 [3 4]]
[[ 1]
 [25]
 [ 9]]


In [42]:
[A, b] =np.random.permutation(np.array([A, b]), axis=0)

TypeError: permutation() takes no keyword arguments

In [13]:
import numpy 
lis = np.random.permutation(3)

In [14]:
A[lis] 

array([[1, 2],
       [5, 6],
       [3, 4]])

In [4]:
dic = {'Ali': [[1],[2],[3]], 'Reza':[[1],[4],[9]]}
print(dic['Ali'][1],dic["Reza"][1])

[2] [4]


In [7]:

dic['Ali'].append([4])
dic["Reza"].append([16])

In [9]:
print(dic['Ali'][3],dic["Reza"][3])

[4] [16]


In [10]:
dic

{'Ali': [[1], [2], [3], [4]], 'Reza': [[1], [4], [9], [16]]}

In [12]:
A = np.array([[1,5,3],[2,4,0]])

In [13]:
A

array([[1, 5, 3],
       [2, 4, 0]])

In [14]:
mean = np.mean(A, axis=0)

In [15]:
mean

array([ 1.5,  4.5,  1.5])

In [16]:
A - mean

array([[-0.5,  0.5,  1.5],
       [ 0.5, -0.5, -1.5]])

In [46]:
y = np.array([1.,-1.,1.,-1.,-1.])
f = np.array([2.,-3.,0.,1.,-1.])

In [59]:
L = 1- np.multiply(y, f)
print(L,L.shape, len(L))
np.maximum(0,1)
hinge = np.maximum(0,L)
print(hinge)
# hinge = np.array([np.max(0.,L[i]) for i in range(len(L))])

[-1. -2.  1.  2.  0.] (5,) 5
[ 0.  0.  1.  2.  0.]


In [68]:
f = np.array([ 1.,-1.,1.,-1.,-1.])
x = np.array([[0., 0.,0., 0.,0.],[1.0,0.,0.,0.,-1.],[0.,0.,0.,-1.,0.],[1.0,-1.,0.0,2.,-2.]])

In [69]:
x

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0., -1.,  0.],
       [ 1., -1.,  0.,  2., -2.]])

In [72]:
L = np.multiply(f,x)
L

array([[ 0., -0.,  0., -0., -0.],
       [ 1., -0.,  0., -0.,  1.],
       [ 0., -0.,  0.,  1., -0.],
       [ 1.,  1.,  0., -2.,  2.]])

In [76]:

F = np.maximum(0,L)
F

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 1.,  1.,  0.,  0.,  2.]])

In [80]:
np.sum(F, axis=0)

array([ 2.,  1.,  0.,  1.,  3.])

In [81]:
np.sum(F, axis=1)

array([ 0.,  2.,  1.,  4.])

In [ ]:
"""
Train model and eval model helpers.
"""
from __future__ import print_function

import numpy as np
import cvxopt
import cvxopt.solvers


def train_model(data, model, learning_rate=0.001, batch_size=16,
                num_steps=1000, shuffle=True):
    """Implements the training loop of stochastic gradient descent.

    Performs stochastic gradient descent with the indicated batch_size.

    If shuffle is true:
        Shuffle data at every epoch, including the 0th epoch.

    If the number of example is not divisible by batch_size, the last batch
    will simply be the remaining examples.

    Args:
        data(dict): Data loaded from io_tools
        model(LinearModel): Initialized linear model.
        learning_rate(float): Learning rate of your choice
        batch_size(int): Batch size of your choise.
        num_steps(int): Number of steps to run the updated.
        shuffle(bool): Whether to shuffle data at every epoch.

    Returns:
        model(LinearModel): Returns a trained model.
    """

    # Performs gradient descent. (This function will not be graded.)
   
    x = data['image']
    y = data['label'].reshape(-1,1)
    batch_num = int(np.ceil(len(x)/batch_size))
    for epoch in range(num_steps):
        if shuffle:
            import random
            permutation = np.random.permutation(x.shape[0])
            x = np.array(x[permutation])
            y = np.array(y[permutation])
        for batch in range(batch_num):
            print("shape of y  :", y.shape)
            batch_start = batch * batch_size
            batch_end = (batch + 1 ) * batch_size 
            if batch+1 == batch_num:
                batch_end = len(x)
            x_batch = np.array([x[i] for i in range(batch_start, batch_end)])
            y_batch = y[batch_start:batch_end]
            print(y_batch.shape)

            update_step(x_batch, y_batch, model, learning_rate)
            
            
        
    return model



def update_step(x_batch, y_batch, model, learning_rate):
    """Performs on single update step, (i.e. forward then backward).

    Args:
        x_batch(numpy.ndarray): input data of dimension (N, ndims).
        y_batch(numpy.ndarray): label data of dimension (N, 1).
        model(LinearModel): Initialized linear model.
    """
    f = model.forward(x_batch)
    total_grad = model.backward(f, y_batch)
    model.w = model.w - learning_rate * total_grad

def train_model_qp(data, model):
    """Computes and sets the optimal model wegiths (model.w) using a QP solver.

    Args:
        data(dict): Data from utils.data_tools.preprocess_data.
        model(SupportVectorMachine): Support vector machine model.
    """
    P, q, G, h = qp_helper(data, model)
    P = cvxopt.matrix(P, P.shape, 'd')
    q = cvxopt.matrix(q, q.shape, 'd')
    G = cvxopt.matrix(G, G.shape, 'd')
    h = cvxopt.matrix(h, h.shape, 'd')
    sol = cvxopt.solvers.qp(P, q, G, h)
    z = np.array(sol['x'])
    # Implementation here (do not modify the code above)
    pass
    # Set model.w
    model.w = None


def qp_helper(data, model):
    """Prepares arguments for the qpsolver.

    Args:
        data(dict): Data from utils.data_tools.preprocess_data.
        model(SupportVectorMachine): Support vector machine model.

    Returns:
        P(numpy.ndarray): P matrix in the qp program.
        q(numpy.ndarray): q matrix in the qp program.
        G(numpy.ndarray): G matrix in the qp program.
        h(numpy.ndarray): h matrix in the qp program.
    """
    P = None
    q = None
    G = None
    h = None
    # Implementation here.
    return P, q, G, h


def eval_model(data, model):
    """Performs evaluation on a dataset.

    Args:
        data(dict): Data loaded from io_tools.
        model(LinearModel): Initialized linear model.

    Returns:
        loss(float): model loss on data.
        acc(float): model accuracy on data.
    """
    # Implementation here.
    f = model.forward(data['image'])
    pred = model.predict(f).astype(int)
    y = data['label'].astype(int)
    loss = model.total_loss(f, processed_dataset[1]) + model.w_decay_factor * np.sum(np.power(model.w,2))
    acc = np.sum([1 if y[i] == pred[i] else 0  for i in range(len(y))]) /len(y)
    return loss, acc
