In [ ]:
"""Main function for train, eval, and test."""

from __future__ import print_function
from __future__ import absolute_import

import numpy as np
import tensorflow as tf

from models.linear_regression import LinearRegression
from train_eval_model import train_model, eval_model, train_model_analytic
from utils.io_tools import read_dataset
from utils.data_tools import preprocess_data
from utils.plot_tools import plot_x_vs_y


In [ ]:
learning_rate = 1.0E-15
w_decay_factor = 0.0001
num_steps = 1000000#FLAGS.num_steps
opt_method = 'analytic'#FLAGS.opt_method
feature_columns = ('BldgType,OverallQual').split(',')
# GarageArea

In [ ]:
dataset = read_dataset("data/train.csv")

In [15]:
train_set = preprocess_data(dataset, feature_columns=feature_columns,
                                squared_features=True)
print(train_set[0][1])
train_set1 = preprocess_data(dataset, feature_columns=feature_columns,
                                squared_features=True)
print(train_set1[0][1])
print(train_set[0][1]**2 )


[  1.   0.   0.   0.   0.  25.]
[  1.   0.   0.   0.   0.  25.]
[   1.    0.    0.    0.    0.  625.]


In [ ]:
ndim = train_set[0].shape[1]
model = LinearRegression(ndim, 'ones')
# print(train_set[0].shape[0])


In [ ]:
#train_model_analytic(train_set, model)
f = model.forward(train_set[0])
print((f.shape, type(f[0])))
#print(f[0], y[0])


In [ ]:
#print(model.backward(0,0))
# y = np.array(train_set[1]).astype(float)
# x = np.array(train_set[0]).astype(float)

In [8]:
#train_model_analytic(train_set, model)
# total_grad = model.backward(f, y)
# print(total_grad)

In [9]:
# print(total_grad.shape)

In [10]:
#print(model.x)
f = model.forward(train_set[0])
#print(f)

In [ ]:
# train_model_analytic(train_set, model)


In [ ]:
print(np.linalg.det(np.dot(np.transpose(model.x), model.x)))

In [ ]:
train_model(train_set, model, learning_rate, num_steps=num_steps)
print('Performed gradient descent.')

In [ ]:
print(model.w)

In [16]:
#print((model.w-train_model_analytic(train_set, model))/np.max(model.w))
train_model_analytic(train_set, model)


[[ 19612.69697571]
 [ 16487.52338409]
 [ 19844.53637314]
 [-12656.34487534]
 [-27238.18854523]
 [  3816.26553416]
 [ 16050.22335052]]


array([[ 19612.69697571],
       [ 16487.52338409],
       [ 19844.53637314],
       [-12656.34487534],
       [-27238.18854523],
       [  3816.26553416],
       [ 16050.22335052]])

In [17]:
print(eval_model(train_set, model))

975593911519.0
