In [1]:
"""Main function for train, eval, and test. (This file will not be graded.)"""

from __future__ import print_function
from __future__ import absolute_import

import numpy as np
import tensorflow as tf

from models.support_vector_machine import SupportVectorMachine
from train_eval_model import train_model, eval_model, train_model_qp
from utils.io_tools import read_dataset
from utils.data_tools import preprocess_data


# flags = tf.app.flags
# FLAGS = flags.FLAGS
# flags.DEFINE_float('learning_rate', 0.001, 'Initial learning rate.')
# flags.DEFINE_float('w_decay_factor', 0.001, 'Weight decay factor.')
# flags.DEFINE_integer('num_steps', 5000, 'Number of update steps to run.')
# flags.DEFINE_string(
#     'feature_type',
#     'default',
#     'Feature type, supports [raw, deafult, custom]')
# flags.DEFINE_string('opt_method', 'iter', 'Supports ["iter", "qp"]')


# def main(_):
#     """High level pipeline.
#     This script performs the trainsing, evaling and testing state of the model.
#     """
    
'''
if __name__ == '__main__':
    tf.app.run()
'''

"\nif __name__ == '__main__':\n    tf.app.run()\n"

In [2]:
learning_rate = 0.001
w_decay_factor = 0.001
num_steps = 5000
opt_method = 'iter'
feature_type = 'default'

# Load dataset and data processing.
train_set = read_dataset("data/train.txt", "data/image_data/")
train_set = preprocess_data(train_set, feature_type)

    # Initialize model.
ndim = train_set['image'][0].shape[0]
print(ndim)
model = SupportVectorMachine(ndim, 'ones', w_decay_factor=w_decay_factor)
print(model.w.shape)
print(model.ndims)
# print(model.w)
#print(train_set['label'])

(1000, 8, 8, 3)
192
(193, 1)
192


In [3]:
#print(model.predict(train_set['image']))
print(eval_model(train_set, model))
print(model.backward(model.forward(train_set['image']), train_set['label']).shape)

(204.80889273725489, 0.91800000000000004)
(193, 1)


In [4]:

    # Train model.
if opt_method == 'iter':
    # Perform gradient descent.
    train_model(train_set, model, learning_rate, num_steps=num_steps)
    print('Performed gradient descent.')
else:
    # Compute closed form solution.
    train_model_qp(train_set, model)
    print('Finished QP Solver')
    train_loss, train_acc = eval_model(train_set, model)
    print("Train loss: %s" % train_loss)
    print("Train acc: %s" % train_acc)

#


189.954298114
175.758687355
162.978168064
151.418441805
140.484876842
130.619504538
121.946452015
114.00223171
106.56424541
99.5516311473
92.707343795
86.66418581
81.7036282053
77.1608701697
72.8663801673
68.7406327997
64.9568214269
61.3104912184
57.8788691508
54.4716537727
51.1392294962
48.2333694491
45.5995143861
43.0661336536
42.2768149677
42.2265458078
42.0733847026
42.2315888284
42.232133405
42.2348936521
42.0287298742
42.1329863658
42.4473688426
42.2897633802
41.9801304055
41.9291810623
41.9817089291
41.982495932
41.9315543313
41.9323489702
42.0883512046
42.0374104879
41.9864682601
41.8837874076
41.8845857738
42.2475394981
42.1448607999
41.9387168207
41.9395188852
42.0437938361
41.785915018
41.7349841578
41.8910004856
41.8918106308
41.9443565631
41.9969010675
41.6355546136
41.7398360068
41.5337015684
41.6379839796
41.8457454851
41.484405072
41.5886960341
41.5377792572
41.6420704558
41.7463620001
41.695448565
41.5410575813
41.5936187335
41.5427047939
41.5952644558
41.6995665287
41

In [5]:
# Eval model.
eval_set = read_dataset("data/val.txt", "data/image_data/")
eval_set = preprocess_data(eval_set, feature_type)
eval_loss, eval_acc = eval_model(eval_set, model)
print("Eval loss: %s" % eval_loss)
print("Eval acc: %s" % eval_acc)

# Test model.
test_set = read_dataset("data/test.txt", "data/image_data/")
test_set = preprocess_data(test_set, feature_type)
test_loss, test_acc = eval_model(test_set, model)    
print("Test loss: %s" % test_loss)
print("Test ac: %s" % test_acc)

(250, 8, 8, 3)
Eval loss: 11.3982207553
Eval acc: 0.98
(250, 8, 8, 3)
Test loss: 12.4754806799
Test ac: 0.976


In [11]:
G = np.eye(8)

In [26]:
model.ndims


192

In [49]:
y = np.ones((4,1))
x = np.random.uniform(0,1,(4,5))
G[0:4,0:5] = np.multiply(y,x)
G

array([[ 0.90595646,  0.57331172,  0.25101878,  0.36791864,  0.41962987,
         0.        ,  0.        ,  0.        ],
       [ 0.80977144,  0.43049315,  0.20625733,  0.36971444,  0.99705965,
         0.        ,  0.        ,  0.        ],
       [ 0.90141659,  0.31906774,  0.50156137,  0.3910382 ,  0.76631391,
         0.        ,  0.        ,  0.        ],
       [ 0.13739785,  0.279245  ,  0.51994244,  0.18766958,  0.99150623,
         0.        ,  0.        ,  0.        ],
       [ 1.76461724,  1.51256037,  2.83411693,  2.45833856,  1.30568758,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ]])

In [43]:
np.multiply(y,x)

array([[  6.69053493e-01,   5.93031985e-01,   9.06460820e-01,
          2.23549610e-01,   1.37138851e-01],
       [  1.33649272e-01,   1.91292123e-01,   4.13583763e-01,
          5.45730833e-01,   7.26692083e-01],
       [  6.74124198e-01,   8.46870525e-04,   5.52422948e-01,
          8.73430204e-01,   3.38935736e-01],
       [  2.87790278e-01,   7.27389393e-01,   9.61649399e-01,
          8.15627918e-01,   1.02920907e-01]])

In [25]:
for i in range(2,10):
    print(i)

2
3
4
5
6
7
8
9


In [51]:
xx = train_set['image']
yy = train_set['label']
dim = xx.shape[0]
r = np.ones((dim, 1))
xx = np.append(xx, r, axis=1)
P = model.w_decay_factor*np.append(np.append(np.identity(xx.shape[1]),np.zeros((xx.shape[1],xx.shape[0])),axis=1),np.zeros((xx.shape[0],xx.shape[1]+xx.shape[0])),axis=0)
q = np.transpose(np.append(np.zeros((1,xx.shape[1])),np.ones((1,xx.shape[0])),axis=1))
G = np.append(np.append(-yy*xx,-np.identity(xx.shape[0]),axis=1),np.append(np.zeros((xx.shape)),-np.identity(xx.shape[0]),axis=1),axis=0)
h = np.append(-np.ones((xx.shape[0],1)),np.zeros((xx.shape[0],1)),axis=0)
    # Implementation here.
#     return P, q, G, h

In [52]:
G.shape

(2000, 1193)

In [53]:
P.shape

(1193, 1193)

In [54]:
q.shape

(1193, 1)

In [55]:
h.shape

(2000, 1)

In [56]:
h

array([[-1.],
       [-1.],
       [-1.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])