In [46]:
import tensorflow as tf
#import cv2
#import .pong_game as game
import random
import numpy as np
from collections import deque

In [28]:
sum =0
cnt = 10000000
for i in range(cnt):
    sum +=np.random.randint(0,3)
sum/cnt

1.000276

In [165]:
cnt=100
sum =0
for i in range(cnt):
    sum +=np.random.choice([0,1], p=[0.4, 0.6] )
sum/cnt

0.55000000000000004

In [166]:
V = np.array([[1, 1,2],[2,2,2],[3,3,3]])

In [167]:
V

array([[1, 1, 2],
       [2, 2, 2],
       [3, 3, 3]])

In [168]:
A = np.stack((V, V, V, V), axis=2)

In [169]:
A

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [174]:
(A[:,:,3]).shape

(3, 3)

In [175]:
A[:,:,3] = V

In [180]:
A[:,:,3] = V**2

In [181]:
C = np.zeros_like(A)

In [182]:
A

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [2, 2, 2, 4]],

       [[2, 2, 2, 4],
        [2, 2, 2, 4],
        [2, 2, 2, 4]],

       [[3, 3, 3, 9],
        [3, 3, 3, 9],
        [3, 3, 3, 9]]])

In [185]:
A[:,:,:] = A[:,:,:]

In [188]:
np.append(A[:,:,1:],[V], axis=2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly